### ISSUE TITLE
section 5.1 PRIORITY frame and idle state clarification

### ISSUE THREAD

**Issue by Scottmitch** [http2/http2-spec#667]
[section 5.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-16#section-5.1) has the following text:
>idle:
      All streams start in the "idle" state.  In this state, no frames
      have been exchanged.

It seems like PRIORITY frames can be sent/received in the IDLE state without causing a state transition as illustrated in [figure 2](http://http2.github.io/http2-spec/#StreamStatesFigure).  If I am interpreting this correctly then the `no frames have been exchanged` statement is not necessarily correct if PRIORITY frames have been exchanged.

**Comment by Scottmitch** [comment]
Any thoughts for the preferred way to clarify this?  Removing the `In this state, no frames have been exchanged.` statement will be sufficient but we may then be missing the original meaning this sentence was meant to convey.

**Comment by martinthomson** [comment]
Closed by #684
