### ISSUE TITLE
Proposal: 'Fragment-Scope' header to control application of fragments after redirects

### ISSUE THREAD

**Issue by hillbrad** [http2/http2-spec#673]
A recurring weakness with OAuth and related capability URL usages (http://www.w3.org/TR/capability-urls/) is the reapplication of URL fragments on redirects:

http://tools.ietf.org/html/rfc7231#section-9.5

This behavior is frequently abused in combination with resources that act as open redirectors to leak sensitive information in a fragment.

I would like to suggest an additional header, 'Fragment-Scope' that could be sent with a Location header on a 3xx to control the disposition of a fragment after a redirect.  Values would be 'no-redirect' which would instruct the user agent to discard the fragment on any subsequent redirect, or 'same-origin' which would discard the fragment after any non-same-origin redirect.  The scope rule, once set, would remain until the user agent terminates following redirects. (so a 'same-origin' policy could not be stripped by redirecting to a second open-redirector in the same origin, and then off-origin from there)

**Comment by hillbrad** [comment]
@isciurus

**Comment by hillbrad** [comment]
Wrong repo, sorry.

**Comment by mnot** [comment]
Brought up on-list:
  http://www.w3.org/mid/1678D864-FFE3-447F-BC35-F5487E48123A@mnot.net
