### ISSUE TITLE
New safe methods

### ISSUE THREAD

**Issue by martinthomson** [http2/http2-spec#679]
> If a client receives a PUSH_PROMISE that does not include a complete 
and valid set of header fields, or the :method header field identifies a 
method that is not safe, it MUST respond with a stream error (Section 
5.4.2) of type PROTOCOL_ERROR.

New safe methods can be defined. Does this mean that the client needs to 
respond with a stream error for methods *not known to be safe*?

See http://www.w3.org/mid/54B53822.2020104@gmx.de

**Comment by jasnell** [comment]
That would be the only logical conclusion. If the client cannot determine if the method is safe, it must assume that it is not.

**Comment by martinthomson** [comment]
Indeed.  We just need to fix it.
