### ISSUE TITLE
Error code not defined for GOAWAY frames smaller than 8 octets?

### ISSUE THREAD

**Issue by kazuho** [http2/http2-spec#691]
For most frames the spec. is clear on which error code should be sent.  For example, 6.9 states:

> A WINDOW_UPDATE frame with a length other than 4 octets MUST be treated as a connection error (Section 5.4.1) of type FRAME_SIZE_ERROR.

But such definition does not seem to exist for GOAWAY (6.8).

**Comment by martinthomson** [comment]
> An endpoint MUST send a FRAME_SIZE_ERROR error if a frame exceeds the size defined in SETTINGS_MAX_FRAME_SIZE, any limit defined for the frame type, or it is too small to contain mandatory frame data.
-- http://http2.github.io/http2-spec/#FrameSize

**Comment by kazuho** [comment]
Thank you for the clarification.  I must have missed it.
