### ISSUE TITLE
COMPRESSION_ERROR language

### ISSUE THREAD

**Issue by RobbySimpson** [http2/http2-spec#695]
(Editorial)

draft-ietf-httpbis-http2 states (Section 4.3):
"A receiver MUST terminate the connection with a connection error (Section 5.4.1) of type COMPRESSION_ERROR if it does not decompress a header block. "
This is the only real discussion of COMPRESSION_ERROR.

draft-ietf-httpbis-header-compression mentions decoding errors four times:
(2.3.3):
"Indices strictly greater than the sum of the lengths of both tables MUST be treated as a decoding error."
(5.1):
"Excessively large integer encodings - in value or octet length - MUST be treated as a decoding error."
(5.2):
"A padding strictly longer than 7 bits MUST be treated as a decoding error. A padding not corresponding to the most significant bits of the code for the EOS symbol MUST be treated as a decoding error. A Huffman encoded string literal containing the EOS symbol MUST be treated as a decoding error."
(6.1):
"The index value of 0 is not used. It MUST be treated as a decoding error if found in an indexed header field representation."

Since draft-ietf-httpbis-header-compression consistently uses the phrase "decoding error," I would suggest we incorporate this phrase into the language in draft-ietf-httpbis-http2 to be explicitly clear.

I'll attempt a PR to suggest a (minor) edit.

**Comment by RobbySimpson** [comment]
Submitted PR #696

**Comment by RobbySimpson** [comment]
BTW: This is my first PR on the spec, so go with caution and feedback is appreciated.

**Comment by martinthomson** [comment]
Closed by #699
