### ISSUE TITLE
RFC 2119 disclaimer has an erratum

### ISSUE THREAD

**Issue by GPHemsley** [http2/http2-spec#713]
http://www.rfc-editor.org/errata_search.php?eid=499

**Comment by reschke** [comment]
How is this a problem of the HTTP/2 specs?

**Comment by GPHemsley** [comment]
https://http2.github.io/http2-spec/index.html#rfc.section.2.2

**Comment by martinthomson** [comment]
Using "NOT RECOMMENDED" is NOT RECOMMENDED.  I think we're OK.

**Comment by reschke** [comment]
IDNITS is happy with it, so am I.
