### ISSUE TITLE
Editorial Changes on httpbis-http2-16

### ISSUE THREAD

**Issue by edburns** [http2/http2-spec#715]
Just completed a read through of httpbis-http2-16 and have some editorial changes.

**Comment by edburns** [comment]
Will create pull request from branch H2-16-715-Editorial.

**Comment by edburns** [comment]
I have created Pull Request 08c4b13 for this.

**Comment by martinthomson** [comment]
Thanks for the input.  Ordinarily, I'd take most of the changes.  The document is going to the RFC editor now, so our ability to take changes is extremely limited.  I don't see anything critical, so I'm going to close these.

**Comment by edburns** [comment]
Thanks for your response.  Naturally I'll abide by your ruling, but I would like to know what will become of the changes?  Will they eventually make it into the document or will the errors corrected by this pull request be in the final RFC?

**Comment by martinthomson** [comment]
I have a final chance to make some editorial changes once the RFC editor has gone through the document.  There are a few here that seem valuable, so I'll try to ensure that I get then.  Some of the changes are, I think, not necessary, but others are clearly addressing grammatical errors and the like.  In the end, it depends on what other changes the RFC editor makes as to whether they are needed.

**Comment by edburns** [comment]
This is great news. I have one other one in another branch. I&#39;ll file an issue and submit a pull request. I appreciate your consideration. 

Ed
