### ISSUE TITLE
push_promise frame state clarification

### ISSUE THREAD

**Issue by Scottmitch** [http2/http2-spec#726]
[section-6.6](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.6) has the following clarification added in draft 17:
> PUSH_PROMISE frames MUST be associated with a peer-initiated stream
   that is in either the "open" or "half closed (remote)" state.

Should this be `half closed (local)` instead of `half closed (remote)`?

If not I think we have an inconsistency with [section 5.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5.1) which has the following for the `half closed (remote)` section:
> half closed (remote):
      A stream that is "half closed (remote)" is no longer being used by
      the peer to send frames.  In this state, an endpoint is no longer
      obligated to maintain a receiver flow control window.
      
>If an endpoint receives additional frames for a stream that is in
      this state, other than WINDOW_UPDATE, PRIORITY or RST_STREAM, it
      MUST respond with a stream error (Section 5.4.2) of type
      STREAM_CLOSED.

**Comment by Scottmitch** [comment]
@martinthomson - Any thoughts?  Am I missing something?

**Comment by Scottmitch** [comment]
@martinthomson - Ping.

**Comment by martinthomson** [comment]
This is merely a problem with perspective.  As in, there is none.  I can provide that thusly:
>   PUSH_PROMISE frames MUST be sent on a peer-initiated stream
>    that is in either the "open" or "half closed (remote)" state.

Does that work?

**Comment by Scottmitch** [comment]
This is an improvement. I'm not sure if we can avoid it but it is a bit confusing with respect to [section 5.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5.1):

>A stream that is "half closed (remote)" is no longer being used by
      the peer to send frames.

**Comment by martinthomson** [comment]
I don't think that's a problem.  The (remote) peer isn't sending, but the (local) peer can.

**Comment by Scottmitch** [comment]
Agreed. Ship it :) Thanks!
