### ISSUE TITLE
Some clarifications regarding GOAWAY.

### ISSUE THREAD

**Issue by buchgr** [http2/http2-spec#731]
We are working on a HTTP/2 library and we are a bit confused and we would like to get it right.

Is it correct that after a sender sent a `GOAWAY` frame with some `last stream identifier` to a receiver, the sender may still open new streams, even with stream identifiers higher than the `last stream identifier` sent in the `GOAWAY` frame? That is the `GOAWAY` frame and the `last stream identifier` only limit the ability of the receiver?

If this is correct, and I believe it is, then I find the following sentence in the first paragraph at `6.8 GOAWAY` confusing.

> Once sent, the sender will ignore frames sent on any new streams with identifiers higher than the included last stream identifier.

In my opinion it should say something of the like 

> Once sent, the sender will ignore frames sent on any new streams **created by the receiver** with identifiers higher than the included last stream identifier.

Thanks.

**Comment by Scottmitch** [comment]
I am also intersted in getting clarity on this topic.  It seems what the "spirit" of the [GOAWAY section](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.8) is something like:

Each endpoint maintains the goaway last stream id from its peer.  When a goaway is received then no local streams can be created (i.e. `IDLE` streams can only transition to `CLOSED`), and all local streams with `stream id` > `last stream id` from the goaway frame are closed (or as the spec says `can be treated as if they never existed`).  Remote streams can still be opened, and to ensure a graceful connection shutdown a goaway frame should be sent in response.

**Comment by martinthomson** [comment]
Not quite: Upon receipt of GOAWAY, new streams can be created, but with the following restrictions:
1.  those with stream identifiers higher than the `last stream id` will be ignored.
2. Those with stream identifiers lower or equal are subject to the usual risk of loss, but they *might* be processed.  Success is determined by what happens on the stream, of course.

**Comment by Scottmitch** [comment]
@martinthomson - Can you clarify the following from [section 6.8](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.8):

> Receivers of a GOAWAY frame MUST NOT open additional
   streams on the connection, although a new connection can be
   established for new streams.

This is what lead me to believe that streams can not be "created" after receiving a `GOAWAY`?

**Comment by martinthomson** [comment]
Hmm.  I'd forgotten that.  That is in conflict with the graceful shutdown we've specified.  I think that we need to take this to the list.  This seems like a genuine bug.

**Comment by Scottmitch** [comment]
Thanks for the quick response @martinthomson!  Would you prefer to bring the issue to the list?

**Comment by martinthomson** [comment]
I'm just trying to formulate something.

**Comment by buchgr** [comment]
hmm I see @martinthomson, so after a GOAWAY on neither the receiver nor the sender side new streams are allowed to be created with `identifiers` higher than the `last stream identifier`?

As a follow up, does the `last stream identifier` in the GOAWAY have to be the identifier of a stream that actually exists or could it also just be a "random number"?

**Comment by martinthomson** [comment]
The intent was to say that the *receiver* of a GOAWAY can't create new streams higher than the `last stream id` value in GOAWAY.  Let me check back in tomorrow; maybe fresh eyes will add perspective.

**Comment by tatsuhiro-t** [comment]
So the intention of the change is allow receiver of GOAWAY are still allowed to create stream lower or equal to received last-stream-id, accepting the fact that those streams are  ignored by peer?  As the graceful shutdown process as described in draft 17, server first sending GOAWAY with (2^31) - 1 starts to ignore any *new* streams created by peer and after some time (this ensures that GOAWAY is reached to the client), server sends another GOAWAY with updated last-stream-id where processing has occurred already.

**Comment by martinthomson** [comment]
@tatsuhiro-t, the intent of the change is to not change anything :)

The process has been unclear, but the point is that if you receive GOAWAY with a last-stream-id greater than anything you have initiated, you can use what space remains for new streams.  What that means is that you can issue new requests on that connection while you take the time to create a replacement connection.  This was considered critical for #458.

That means that 2^31-1 serves only as a warning of impending closure, though in theory it need not change any behaviour for the existing connection.  I'd take steps to make a replacement connection though.

**Comment by tatsuhiro-t** [comment]
Thank you for clarification!

**Comment by Scottmitch** [comment]
Here is a link to @martinthomson's doc from the mailing list which provides additional clarity to this issue https://docs.google.com/presentation/d/1yGLlIUqwVy3WeVv8K9HHOSkBietWTjJPlI_pA5wqU-Q/edit#slide=id.p

**Comment by tatsuhiro-t** [comment]
Latest PR is much more comfortable to me. Thanks!
