### ISSUE TITLE
Some questions about Stream Priority

### ISSUE THREAD

**Issue by appchemist** [http2/http2-spec#738]
Dear http2 members.

After reading HTTP/2 specification, There is some curious about Stream Priority.

In First paragraph at "5.3.4 Prioritization State Management", 

> When a stream is removed from the dependency tree, its dependencies
> can be moved to become dependent on the parent of the closed stream.
> The weights of new dependencies are recalculated by distributing the
> weight of the dependency of the closed stream proportionally based on
> the weights of its dependencies.

When a parent stream is closed, these paragraph describes that dependencies's weights are recalculated.

**First Question.**
Without additional HEADERS or PRIORITY frame, Can a Stream's weight that is set by HEADERS or PRIORITY frame be recalculated?
The weight mentioned these paragraph is recalculated.
Just look a word, The weight mentioned these paragraph are equal to a Stream's weight that is set by HEADERS or PRIORITY frame.

In Second paragraph at "5.3.4 Prioritization State Management", 
> Streams that are removed from the dependency tree cause some
> prioritization information to be lost.  Resources are shared between
> streams with the same parent stream, which means that if a stream in
> that set closes or becomes blocked, any spare capacity allocated to a
> stream is distributed to the immediate neighbors of the stream.

If "B" stream is in closed or blocked state, Spare capacity that was allocated to "B" stream is distributed to other neighbors with same parent.
This is my understand.

**Second Question.**
![why](https://cloud.githubusercontent.com/assets/1546031/6983712/2a91b88c-da5c-11e4-86dc-b02260be478f.png)
This is a drawing about a first example in "5.3.4 Prioritization State Management".
Why does "C" stream have a 100 resources? 

**Third Question.**
![why2](https://cloud.githubusercontent.com/assets/1546031/6983961/d04d8984-da5e-11e4-8f61-6308e0e12d2b.png)
This is a drawing about a second example in "5.3.4 Prioritization State Management" For equal starting weights.
Why do "B" and "C" stream have a 20 resources?
Because "D" stream is block, I think that "B" and "C" stream have a 30 resources

**Last Question.**
Is "Flow Control Window" related to "Stream Priority"?

**If this issue is not appropriate in Issues board, I will close or delete this Issue.**
**With sincere thanks**

**Comment by martinthomson** [comment]
This isn't really the right place, but that's OK.

> Without additional HEADERS or PRIORITY frame, Can a Stream's weight that is set by HEADERS or PRIORITY frame be recalculated?

If a stream is removed from the priority tree, then it's weight should be allocated to its children.  As you note, this loses some information.  The parent node's unused resources are always distributed to its children first, rather than its peers.

>  Why does "C" stream have a 100 resources? 

As above, C (and D) gets the resources that A cannot use.

>  Why do "B" and "C" stream have a 20 resources?

"B" and "C" should have 15 each.  And B should continue to have 30.  This is an example of how information is lost by removing A from the tree.  If A was still there, C would get an equal share to B as long as D was blocked.

>  Is "Flow Control Window" related to "Stream Priority"?

Only in the sense that the connection flow control window is a resource that might need to be shared between streams.  And also because it can cause a particular stream to become blocked, thereby preventing allocation of resources to that stream.

**Comment by appchemist** [comment]
Thanks very much ! @martinthomson 

I have more question about second and third question.

I think there are more principles about stream priority.
1. if a stream that doesn't have any dependency is blocked and isn't closed. a stream's weight is not distributed to other neighbors with same parent.
a stream is in tree but these stream is blocked.
a stream's weight is only distributed to child.
2. When a parent stream is blocked and isn't closed. if a dependency that has neighbors with same parent is blocked, a perent stream's weight is not distributed to a dependency that is blocked.

**First Question**
is above a​ssumption right?

**Finally Question**
Are there places that can question about HTTP/2 ?

**Comment by martinthomson** [comment]
1 is right.

>  2. When a parent stream is blocked and isn't closed. if a dependency that has neighbors with same parent is blocked, a perent stream's weight is not distributed to a dependency that is blocked.

Think of it this way:
* Distributing resources to a parent's dependencies is considered the same as distributing to the parent.
* If you can't allocate resources to one stream, find another that can take them.

Finally, if you want to make good progress, it's always better to complete a stream than it is to distribute resources according to priority.

>  Are there places that can question about HTTP/2 ?

I don't know.  StackOverflow and friends are pretty good at this sort of level of detail.

**Comment by appchemist** [comment]
At Your First reply,
> "B" and "C" should have 15 each. And B should continue to have 30. This is an example of how information is lost by removing A from the tree. If A was still there, C would get an equal share to B as long as D was blocked.

"B" and "C" should have 15 each => "D" and "C" shoul have 15 each
is right?

finally, When "A" is removed and "D" is blocked, "D" and "C" shold have 15 each and B should have 30

**Comment by martinthomson** [comment]
Yes.  Though if D is blocked, the split goes from D:1/4-C:1/4-B:2/4 to just C:1/3-B:2/3

**Comment by appchemist** [comment]
@martinthomson sincerely thank you!
