### ISSUE TITLE
HEADERS Stream Dependency State clarification

### ISSUE THREAD

**Issue by Scottmitch** [http2/http2-spec#739]
I don't where the specification discusses the stream state of the `Stream Dependency` stream in the HEADERS frame [section 6.2](http://http2.github.io/http2-spec/index.html#rfc.section.6.2).  The priority frame can be sent on streams in any state, so does that same logic apply to the stream identified by the `Stream Dependency` in the HEADERS frame?  Or is the intention to limit the state to `OPEN`, etc... Either way it would be helpful to clarify what the intentions and expected behavior is.

**Comment by martinthomson** [comment]
I'm not parsing the question very well.  Are you asking what state a stream has to be in to create a dependency on it?

If that's the case, there is no restriction on state.  We don't explicitly say this, but it is effectively covered by this statement:

> All streams are initially assigned a non-exclusive dependency on stream 0x0.

-- [Section 5.3.5](http://http2.github.io/http2-spec/#pri-default)

**Comment by Scottmitch** [comment]
@martinthomson - Sorry.  I restructured the question and should have re-read before clicking create issue...

My question can be demonstrated by a simple example:
1. Connection has been initialized.
2. Local endpoint receives a HEADERS frame with `Stream Id = 3` and `Stream Dependency = 5`.

At this point the `Stream ID = 3` would go through a state transition to OPEN.  The question is that is this OK for the `Stream Dependency` to refer to a stream that has not been "created" yet (i.e. still in IDLE and no frames exchanged)?  So in effect should this action:
1. "create" the stream associated with stream id 5.
2. return some type of error because stream id 5 has not yet been created.

I think option 1 makes sense because "PRIORITY FRAMES can be sent/received at any time".  However this is an assumption and would be nice to see this called out in the specification to ensure consistent behavior.

**Comment by martinthomson** [comment]
Yes, option 1 is what is implied by the referenced statement.  You only need to "create" stream 5 because you might want to track changes.  In some implementations, you could avoid any state for that, since you can fulfill any request for its priority by providing defaults.

**Comment by Scottmitch** [comment]
@martinthomson - So in summary you believe this behavior is clearly defined in the specification and should not be clarified any more?

**Comment by martinthomson** [comment]
Oh, I wouldn't say that it's perfectly clear, but my options for correcting it are exceedingly painful.  In assessing the cost-benefit, I think we'll just have to put this one in the Implementer's Guide.

**Comment by Scottmitch** [comment]
@martinthomson - Thanks for the clarification :).

I haven't looked into it but would it be too painful to reference the PRIORITY section in the HEADERS?  Something like...
```
Stream Dependency:
A 31-bit stream.... The stream this identifies is subject to the same restrictions as if a PRIORITY frame were identifying this stream, see section 6.3
```

**Comment by martinthomson** [comment]
Well, yes, conditional on the same pain associated with any change.  I'm not sure that it addresses your actual concern here though, which relates to states.

I thought that we had text establishing that the priority info in HEADERS was equivalent to PRIORITY anyway.  5.3 only makes it a circumstantial relationship though, I see.

**Comment by Scottmitch** [comment]
Yip I remember that too...

> Prioritization information in a HEADERS frame is logically equivalent to a separate PRIORITY frame, but inclusion in HEADERS avoids the potential for churn in stream prioritization when new streams are created. Prioritization fields in HEADERS frames subsequent to the first on a stream reprioritize the stream (Section 5.3.3).

I think this is sufficient.  Thanks!
