### ISSUE TITLE
GOAWAY + FRAME_SIZE_ERROR?

### ISSUE THREAD

**Issue by daurnimator** [http2/http2-spec#740]
It seems reasonable that a `GOAWAY` frame of <8 bytes should get a `FRAME_SIZE_ERROR`?

**Comment by martinthomson** [comment]
An endpoint MUST send a FRAME_SIZE_ERROR error if a frame exceeds the size defined in SETTINGS_MAX_FRAME_SIZE, any limit defined for the frame type, _or it is too small to contain mandatory frame data_.

-- [Section 4.2](http://http2.github.io/http2-spec/#FrameSize)

**Comment by daurnimator** [comment]
> or it is too small to contain mandatory frame data.
> 
> -- Section 4.2

Ah-ha, I managed to miss that clause.
