### ISSUE TITLE
Behaviour on reserved bits? 

### ISSUE THREAD

**Issue by daurnimator** [http2/http2-spec#741]
What should the behaviour be if a reserved bit is set in certain types of frames? e.g. 
  - `PUSH_PROMISE`
  - `WINDOW_UPDATE`

**Comment by martinthomson** [comment]
A reserved 1-bit field. The semantics of this bit are undefined and the bit MUST remain unset (0x0) when sending and _MUST be ignored when receiving_. 

-- [Section 4.1](http://http2.github.io/http2-spec/#FrameHeader)

**Comment by daurnimator** [comment]
> A reserved 1-bit field. The semantics of this bit are undefined and the bit MUST remain unset (0x0) when sending and MUST be ignored when receiving.
> 
> -- Section 4.1

As written that only applies to the reserved bit in the frame header.

This issue is about the reserved bits inside of various frames.
