### ISSUE TITLE
Data Frame flow control vs error

### ISSUE THREAD

**Issue by Scottmitch** [http2/http2-spec#743]
It seems like the specification is a bit inconsistent across different sections regarding which type of error should be sent when data frames are received in "unexpected states".  It also seems like the spec requires historical information to be kept about streams that have been closed to correctly keep flow control windows in sync.  I'm hoping this is just a misinterpretation but could someone provide clarity?

#### Conflicting error
[section 6.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.1):
> DATA frames are subject to flow control and can only be sent when a
   stream is in the "open" or "half closed (remote)" states.... 
   If a DATA frame is received whose
   stream is not in "open" or "half closed (local)" state, the recipient
   MUST respond with a stream error (Section 5.4.2) of type
   STREAM_CLOSED.

[section 5.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5.1):
> An endpoint MUST NOT send frames other than PRIORITY on a closed
stream. An endpoint that receives any frame other than PRIORITY
after receiving a RST_STREAM MUST treat that as a stream error
(Section 5.4.2) of type STREAM_CLOSED. Similarly, an endpoint
that receives any frames after receiving a frame with the
END_STREAM flag set MUST treat that as a connection error
(Section 5.4.1) of type STREAM_CLOSED, unless the frame is
permitted as described below.

I'm guessing the end result of these two sections is to just follow section 5.1?  Does this also imply that implementations have to keep around historical information on streams that have been closed to be able to respond correctly?

#### Historical state required
[section 5.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5.1):
> Flow controlled frames (i.e., DATA) received after sending
      RST_STREAM are counted toward the connection flow control window.
      Even though these frames might be ignored, because they are sent
      before the sender receives the RST_STREAM, the sender will
      consider the frames to count against the flow control window.

Again this section seems to imply that historical information must be kept (indefinitely?) to know how to handle receiving a DATA frame in an "unexpected" state.

**Comment by martinthomson** [comment]
6.1 does seem to imply that you send STREAM_CLOSED for a stream in the idle state.  Go with 5.1 there.

>  Does this also imply that implementations have to keep around historical information on streams that have been closed to be able to respond correctly?

Not really, if you maintain a set of open streams, the closed streams are any stream not in that set with a number lower than the highest in the same direction.

As for flow control, you only have to account for the connection flow control window.  You are discarding the data anyway, I hope.  You can do even less accounting if you close the stream (which I encourage you to do for crazy cases like that.

**Comment by Scottmitch** [comment]
> Not really, if you maintain a set of open streams, the closed streams are any stream not in that set with a number lower than the highest in the same direction.

The issue is that the requirement (i.e. both are `MUST` statements) of what error to send varies based upon how the stream was closed. 
If a RST_STREAM was used -> stream error
If a END_STREAM was used -> connection error

> As for flow control, you only have to account for the connection flow control window.

The flow control question was also centered on the condition of when it is an error vs when it should be counted against flow control.

**Comment by Scottmitch** [comment]
> 6.1 does seem to imply that you send STREAM_CLOSED for a stream in the idle state. Go with 5.1 there.

Not only that but they are conflicting. Say a stream is in the CLOSED state because of an END_STREAM was sent/received.  Section 5.1 says this should be a stream error, but section 6.1 says this is a connection error.

**Comment by martinthomson** [comment]
>  If a RST_STREAM was used -> stream error
If a END_STREAM was used -> connection error

If you adopt the policy that any error is a connection error, this is not a problem :)

**Comment by Scottmitch** [comment]
> If you adopt the policy that any error is a connection error, this is not a problem :)

Owch...getting technical on me now. Is there a "when in doubt through connection error" clause in the spec :)

@martinthomson - What about the flow control portion of the question?

**Comment by martinthomson** [comment]
I don't quite understand where you are coming from here.  Are you concerned that a DATA frame sent on an idle stream might consume the flow control window for that stream?  I'd go back to the previous answer for that: do you really want to continue talking to a person that is crazy enough to send you DATA frames like that?  Send them a GOAWAY, with an error code of DONT_COME_BACK_UNTIL_YOUVE_SEEN_A_PSYCHIATRIST.

**Comment by Scottmitch** [comment]
> Are you concerned that a DATA frame sent on an idle stream might consume the flow control window for that stream

I am asking for clarification on what the specification dictates must be done when a DATA frame is received on a stream that is not in the "open" or "half closed (local)" states. The specification talks about responding with an error (unclear if stream or connection error is required) and also counting against the connection flow control window (if RST_STREAM is sent). What I'm guessing (and would like clarification / confirmation for) is when a DATA frame is received it MUST be counted against the connection flow control window AND also MAY result in some type of error (depending on stream state).  The reason why I am asking if historical state is required because that is what the specification seems to be implying by imposing `MUST` clauses based on the condition of how a stream was closed.

> do you really want to continue talking to a person that is crazy enough to send you DATA frames like that

Clearly this is not the mainstream use-case, but implementing a library requires one to handle these boundary conditions.  Sending a GO_AWAY does not prevent a peer from sending frames for stream which are `<= Last-Stream-ID` and so it is critical that the connection window be correctly updated.  The `Last-Stream-ID` could be set to 0 but this seems like it may not be semantically correct in all situations.

**Comment by Scottmitch** [comment]
Forgot to include the "assumption" of updating the flow control window is not an assumption be a reference to [section 6.9](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.9):
> A receiver that receives a flow controlled frame MUST always account
   for its contribution against the connection flow control window,
   unless the receiver treats this as a connection error
   (Section 5.4.1).  This is necessary even if the frame is in error.
   Since the sender counts the frame toward the flow control window, if
   the receiver does not, the flow control window at sender and receiver
   can become different.

Per our discussion above it seems like we should always keep the flow control window in sync, but this allows the peer to not update the connection window.  This section seems to overlap with and provide slightly different direction than the sections referenced from the specification above.

**Comment by martinthomson** [comment]
>  Sending a GO_AWAY does not prevent a peer from sending frames for stream which are <= Last-Stream-ID.

True, if you keep the connection open.  I wouldn't.  Exercise your option to close the connection after sending a GOAWAY.  That makes the error more visible as well as reducing your corner-case-handling workload.

> The reason why I am asking if historical state is required because that is what the specification seems to be implying by imposing MUST clauses based on the condition of how a stream was closed.

Yeah, technically, if you want to be compliant, you will need to remember why.  

> this allows the peer to not update the connection window

Not really.  A difference in the flow control window between two peers is _bad_.  I guess that the text assumes that this was obvious.

**Comment by Scottmitch** [comment]
> Yeah, technically, if you want to be compliant, you will need to remember why.

Keeping history is undesirable, and based upon your response it seems that you are either implying there is a way out or recognizing most implementations won't bother?  Is it possible to clarify this to avoid the need to keep history? The spec goes through a good deal of trouble in other places to keep the required amount of state down (flow control windows, etc....). Is what the spec is trying to say something like `if a data frame is received with a stream id that is less than the next stream id to be created then return a stream error of type STREAM_CLOSED (or PROTOCOL_ERROR)`.  A connection error would be implied (from other parts of the spec) if the stream id greater than the next stream id to be used for a new stream.  Even if implementations do keep this state and send the "correct" error I'm not sure what value that provides. This seems like a remnant that hadn't been cleaned up as stream state and frame definitions changed.

> Not really. A difference in the flow control window between two peers is bad. I guess that the text assumes that this was obvious.

Agreed this is bad...hence the issue :)  The specification saying `unless the receiver treats this as a connection error (Section 5.4.1)` is misleading at the very least and possibly an error.  This allows a connection to remain open while in a state such that the connection flow control windows are out of sync.  I think I understand what is "desired" but I believe this portion in the specification is contradicting that meaning.

**Comment by ejona86** [comment]
@Scottmitch, closing the connection is part of the connection error handling (Section 5.4.1):
> After sending the GOAWAY frame for an error condition, the endpoint MUST close the TCP connection.

**Comment by Scottmitch** [comment]
@ejona86 - +1. Thanks for pointing that out. Connection error implies we are not doing graceful shutdown (I think) so I think this may be the best option to take here.  No history needed.  @martinthomson - Sound good...if so feel free to close.

**Comment by EugeneChung** [comment]
I'm still not clear what I have to do for this.

As RFC 7540 says,

5.1.  Stream States
idle:
      Receiving any frame other than HEADERS or PRIORITY on a stream in
      this state MUST be treated as a connection error (Section 5.4.1)
      of type PROTOCOL_ERROR.

6.1.  DATA
   If a DATA frame is received
   whose stream is not in "open" or "half-closed (local)" state, the
   recipient MUST respond with a stream error (Section 5.4.2) of type
   STREAM_CLOSED.

What MUST I have to do follow? The latter case is not considering 'idle' state, I guess?

**Comment by hruellan** [comment]
5.1 and 6.1 are speaking of two different things (idle state, and DATA frames), which have an intersection: receiving a DATA frame in the idle state.
A connection error being "stronger" than a stream error, section 5.1 supersedes section 6.1 in this case. This is described in the spec: 5.4.1 states that a stream error can always be changed to a connection error.

**Comment by kazuho** [comment]
@hruellan 
> A connection error being "stronger" than a stream error, section 5.1 supersedes section 6.1 in this case. This is described in the spec: 5.4.1 states that a stream error can always be changed to a connection error.

Can you also clarify what is the correct error code that should be sent?

* section 5.1 suggests `PROTOCOL_ERROR`
* section 6.1 suggests `STREAM_CLOSED` (and IIUC section 5.4.1 does not allow changing the error code when promoting stream error to a connection error)

FWIW to me this seems like a correction error of the specification.  Apparently in https://lists.w3.org/Archives/Public/ietf-http-wg/2013OctDec/1482.html @martinthomson changed the description in section 6.1 so that it would match the description in section 5.1 _for "closed" or "half-closed (remote)" states_.  However it is likely that that has introduced contradicting statements for "idle", "reserved (local)", "reserved (remote)" states.

**Comment by hruellan** [comment]
The STREAM_CLOSED error code doesn't apply when the stream hasn't been opened yet (i.e. is in the "idle", "reserved (local)", "reserved (remote)" states. So when receiving a DATA frame for a stream in the idle state, the PROTOCOL_ERROR error code should be used.

**Comment by kazuho** [comment]
@hruellan Thank you for the clarification!

**Comment by daurnimator** [comment]
> The STREAM_CLOSED error code doesn't apply when the stream hasn't been opened yet (i.e. is in the "idle", "reserved (local)", "reserved (remote)" states. So when receiving a DATA frame for a stream in the idle state, the PROTOCOL_ERROR error code should be used.

Perhaps we can improve this copy?:

>If a DATA frame is received whose stream is not in "open" or "half-closed (local)" state, the recipient MUST respond with a stream error (Section 5.4.2) of type STREAM_CLOSED.
