### ISSUE TITLE
"h2c" not registered as HTTP Upgrade Token?

### ISSUE THREAD

**Issue by pyfisch** [http2/http2-spec#744]
The section [Starting HTTP/2 for "http" URIs](http://http2.github.io/http2-spec/#rfc.section.3.2) says " The client does so by making an HTTP/1.1 request that includes an Upgrade header field with the "h2c" token.", but why should not the "h2c" token registered in the [Upgrade Token Registry](http://www.iana.org/assignments/http-upgrade-tokens/http-upgrade-tokens.xhtml)? I can't find any reference in the [IANA Considerations](http://http2.github.io/http2-spec/#iana) section registering the token once the RFC gets published.

**Comment by mnot** [comment]
We'll take care of this when the RFC is final.

**Comment by reschke** [comment]
Well, it's in AUTH48 right now, so now is the moment to address this. I'll also have to go back to "IANA evaluation", because the IANA considerations changed.

**Comment by mnot** [comment]
The registry is FCFS; the template doesn't have to be in this spec.

It may be unfortunate that it's not in there, but going back to IANA eval for something this small doesn't make sense.

**Comment by sprstnd** [comment]
sure it does. do it right the first time.

**Comment by mnot** [comment]
@sprstnd the spec has been published, and the token is registered, so arguing the point isn't productive now. Please keep discussion on-topic.
