### ISSUE TITLE
"allocate resources proportionally based on their weight" is a source of confusion

### ISSUE THREAD

**Issue by igrigorik** [http2/http2-spec#747]
https://httpwg.github.io/specs/rfc7540.html#rfc.section.5.3.2

> All dependent streams are allocated an integer weight between 1 and 256 (inclusive).
> 
> Streams with the same parent SHOULD be allocated resources proportionally based on their weight. Thus, if stream B depends on stream A with weight 4, stream C depends on stream A with weight 12, and no progress can be made on stream A, stream B ideally receives one-third of the resources allocated to stream C.

This section, more so than any others, has been a consistent source of developer confusion. E.g..

> Can you further explain how "resource A has a weight of 12, and B a weight of 4" leads to "A should receive two-thirds of available resources" according to "proportional weights." In my mind you'd add 12+4=16 and take the proporition out of 16, like B would receive 4/16 or one quarter of available resources. I can't really see any way you get "thirds" in this scenario, unless you take 4/12, but that doesn't explain A's "thirds" (from 12/12).

Can we more clearly define this behavior? Ideally, in the spec, and if not possible at least as an FAQ entry somewhere else?

**Comment by kazu-yamamoto** [comment]
@igrigorik In the RFC7540 example, B has 4 and C has 12. Thus,

- B/C = 4/12 = 1/3 which RFC 7540 explains
- B/total = B/(B+C) = 4 / (4 + 12) = 1/4

In your HPBN example, A has 12 and B has 4

- A/B = 12/4 = 3
- A/total = A/(A+B) = 12/(12+4) = 3/4

So, A should receive *three-quarters* of available resources.

**Comment by kazu-yamamoto** [comment]
Readers might want the second calculation but RFC 7540 uses the first calculation. I guess that's why readers might feel that section.5.3.2 is a little bit confusing.

**Comment by mnot** [comment]
See:
  http://http2.github.io/faq/#is-the-priority-example-in-section-532-incorrect

**Comment by kazu-yamamoto** [comment]
@igrigorik Are you satisfied with this answer? If so, please update HPBN.

**Comment by igrigorik** [comment]
Done, ptal: http://chimera.labs.oreilly.com/books/1230000000545/ch12.html#HTTP2_PRIORITIZATION - does that look correct? :)

**Comment by martinthomson** [comment]
LGTM

**Comment by kazu-yamamoto** [comment]
:+1:

**Comment by summerwind** [comment]
:+1:
