### ISSUE TITLE
Save initial files into cache storage instead of browser's cache

### ISSUE THREAD

**Issue by tresdin** [http2/http2-spec#750]
At this time, there is no way to save intial files which are fetched at the very first HTTP request into [`CacheStorage`](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#cache-storage). I'm thinking about having a header that handles this issue.
`Cache-Control : location=cache-storage`
Then developers can easily retrieve those files saved in cache storage on client side.
```
CacheStrorage.open('main').then(cache => {
    cache.match('/path/to/initFile').then(response => {
        console.log('File exists in cache storage');
    });
});

**Comment by martinthomson** [comment]
This isn't the appropriate place to make that sort of request.  This is the protocol, not the API.  You might like to try slightlyoff/ServiceWorker instead.
