### ISSUE TITLE
Swoole already supports http2, please add to the list

### ISSUE THREAD

**Issue by matyhtf** [http2/http2-spec#751]
Swoole is an event-driven asynchronous & concurrent networking engine with high performance for PHP.
https://github.com/swoole/swoole-src

Swoole is already support http2 in the version 1.8.22.
https://github.com/swoole/swoole-src/releases/tag/swoole-1.8.2-stable

name: swoole
language: php
role(s): server
negotiation(s):	ALPN, NPN
protocol id(s): h2

sample
-----
```php
$ssl_dir = realpath('../../tests/ssl');
$serv = new swoole_http_server("0.0.0.0", 9501, SWOOLE_BASE, SWOOLE_SOCK_TCP | SWOOLE_SSL);
$serv->set([
    'ssl_cert_file' => $ssl_dir . '/ssl.crt',
    'ssl_key_file' => $ssl_dir . '/ssl.key',
    'open_http2_protocol' => true,
]);
 
$serv->on('Request', function(swoole_http_request $request, swoole_http_response $response) {
    $response->end("<h1>Hello Swoole!</h1>\n");
});
 
$serv->start();
```

**Comment by mnot** [comment]
This isn't the appropriate place to record implementations; see the wiki:
  https://github.com/http2/http2-spec/wiki/Implementations

**Comment by matyhtf** [comment]
OK, thanks.
