### ISSUE TITLE
Suggestion: add recommended NGINX server configuration to wiki

### ISSUE THREAD

**Issue by rundowncreator** [http2/http2-spec#755]
We've been using SPDY in production for a while now, and with Ubuntu 16.04/Nginx 1.10.0 out, we were hoping to transition to HTTP/2.  But, we've been having a hard time deploying it (and might just scrap it for now) because of its strict cipher requirements.

We have `ssl_prefer_server_ciphers` set to `on` for security reasons.  With NGINX, `ssl_ciphers` defaults to `HIGH:!aNULL:!MD5`, but that causes a `ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY` error in Chrome when used with HTTP/2.

I've seen the spec's [ciphers blacklist](http://http2.github.io/http2-spec/index.html#BadCipherSuites), but as a developer and not a cryptographic expert, this stuff makes me feel like my head is going to explode.

I've tried Googling what to specify for `ssl_ciphers` when using HTTP/2, but everyone recommends something different, so it's hard to know what's right and what's wrong.

Anyways, I would like to humbly suggest you add some recommended NGINX (and maybe Apache) server config files to the wiki, that would work on popular OSes with the latest version of OpenSSL.  It would make it a lot easier for people like me to deploy HTTP/2.

Thanks for all of your hard work.

-Jeff

**Comment by Scottmitch** [comment]
Seems like it would be more appropriate to reach out to the NGINX team for support.

**Comment by rundowncreator** [comment]
I agree that it would be ideal if NGINX's default value for `ssl_ciphers` were compatible with the HTTP/2 spec.  I've reported [the issue](https://trac.nginx.org/nginx/ticket/987#ticket) to the NGINX team.

<two_cents>
That said, I still think the HTTP/2 wiki would benefit greatly from a section on recommended ciphers.  If you're going to take a stand on ciphers by blacklisting 276 of them, why not recommend some ciphers to use instead?  Because saying "don't do this" is not as useful as saying "don't do this, do this instead."
</two_cents>

**Comment by HansVanEijsden** [comment]
I know it depends on the SSL version, but the directives on https://cipherli.st are giving me an A+ on SSLLabs (with OpenSSL 1.0.2h). Yes, I think It would be great if NGINX could change the default ciphers. The more A or A+, the better imho.

**Comment by mnot** [comment]
The WG chose to document a blacklist rather than a whitelist because it allows future (and presumably better) ciphers. It's not appropriate to recommend specific ciphers or configurations, because we don't have consensus to do that, and that sort of information is likely to go out of date quickly.

This really needs to come from your implementation.

**Comment by rundowncreator** [comment]
Well, then perhaps just adding some links to the the wiki would be a good compromise?  Maybe https://cipherli.st/ and https://www.ssllabs.com/ssltest/, or whatever else you guys think are good resources.

Right now, NGINX's default config is not compatible with HTTP/2.  I've reported the issue to them, and I hope they fix it, but in the mean time, something as simple as a few links on the wiki could really make deploying a lot easier for other developers/sysadmins who aren't crypto experts.

**Comment by daurnimator** [comment]
This repository is for the *standard*, a "permanent" document it provide minimum security standards set at the time the standard was released. As time goes on new vulnerabilities will be discovered, and computers will get more powerful. Things currently considered secure will no longer be secure. In 10 years, nginx may not even exist, but this standard will remain unchanged. It's a bad idea to put any such specific advice into it.

> Right now, NGINX's default config is not compatible with HTTP/2. I've reported the issue to them, and I hope they fix it

They should.

> in the mean time

As noted above, this is not a place for temporary/"mean time" solutions.

> on the wiki could really make deploying a lot easier for other developers/sysadmins who aren't crypto experts.

Personally I'm not sure why a sysadmin would ever really find their way here. This repository is mainly for implementors of http2 servers/clients/tools.

-------------------------

That said, https://mozilla.github.io/server-side-tls/ssl-config-generator/ is (currently) a great link for generating secure TLS configurations for popular webservers. I recommend you bookmark it for your own purposes :)
