### ISSUE TITLE
Invalid link in "What does HTTP/2 do to improve security?" section in FAQs

### ISSUE THREAD

**Issue by ipeychev** [http2/http2-spec#756]
Hello,

There is an invalid link (returns 404) in "What does HTTP/2 do to improve security?" section in FAQs. The link is supposed to navigate to the draft about "opportunistic encryption".

Thanks,

**Comment by ipeychev** [comment]
The right repository seems to be [this](https://github.com/http2/http2.github.io/tree/master/faq ) one, but there is no "issues" section. Please feel free to close this issue if opening in this way is agains the policies.

Thanks,

**Comment by mnot** [comment]
Fixed, thanks!
