### ISSUE TITLE
Implementations: Chromium removed NPN

### ISSUE THREAD

**Issue by neilstuartcraig** [http2/http2-spec#757]
Hi

I was just having a look at the implementations page and noticed that NPN is listed for Chromium. NPN was removed in July in Chromium which made it into Chrome 51. Am I OK to edit the page and either remove NPN from the Chromium listing or to note that it's <v51?

Source: https://developers.google.com/web/updates/2016/04/chrome-51-deprecations#remove_tls_next_protocol_negotiation_npn

Cheers

**Comment by martinthomson** [comment]
Yes, you should feel free to edit the wiki.

BTW, Firefox recently removed NPN as well.
