### ISSUE TITLE
questions about stalled time

### ISSUE THREAD

**Issue by feifeipan** [http2/http2-spec#761]
I have a page include 100 images. In chrome network panel, I found stalled time and request sent time cost so much. 

![2017-04-05 1 26 54_1](https://cloud.githubusercontent.com/assets/2155605/24694025/e5df6862-1a12-11e7-902d-bdcb9eaee791.png)

![2017-04-05 1 35 18_1](https://cloud.githubusercontent.com/assets/2155605/24694329/0f53fc48-1a14-11e7-87e2-8eedc86d1a90.png)

then i check the session detail. After sent 1.jpg_.webp, the client began to “ HTTP2_SESSION_RECV_DATA” , when finish receiving, send " HTTP2_SESSION_PING" get “ack", finally continue to send request.
![2017-04-05 1 28 52_1](https://cloud.githubusercontent.com/assets/2155605/24694747/afbbbf80-1a15-11e7-9daa-81ce6c9c2065.png)
![2017-04-05 1 29 20_1](https://cloud.githubusercontent.com/assets/2155605/24694756/b95e1f9c-1a15-11e7-853c-a430d1103ed2.png)

I'm wondering if there is a limitation for client to send request. http/1.x have 6 request. what's the limitation for http/2?

Thanks a lot.

**Comment by Scottmitch** [comment]
https://tools.ietf.org/html/rfc7540#section-5.1.2

> A peer can limit the number of concurrently active streams using the
   SETTINGS_MAX_CONCURRENT_STREAMS parameter (see Section 6.5.2) within
   a SETTINGS frame.  The maximum concurrent streams setting is specific
   to each endpoint and applies only to the peer that receives the
   setting.  That is, clients specify the maximum number of concurrent
   streams the server can initiate, and servers specify the maximum
   number of concurrent streams the client can initiate.

Consider opening an issue against the browser/server if you expect different behavior. This doesn't seem like a limitation of the spec.

**Comment by feifeipan** [comment]
Thanks. 

The spec says there no limit to this value. But in my case , after only 6 request sent, the client stops sending request. After finish receiving stream 1225 and get an ack response, the client continue to send other request.

the max_concurrent setting failed? Or the client is waiting for an ack response?

> SETTINGS_MAX_CONCURRENT_STREAMS (0x3):  Indicates the maximum number
      of concurrent streams that the sender will allow.  This limit is
      directional: it applies to the number of streams that the sender
      permits the receiver to create.  Initially, there is no limit to
      this value.  It is recommended that this value be no smaller than
      100, so as to not unnecessarily limit parallelism.

**Comment by martinthomson** [comment]
As @Scottmitch says, this is likely an issue with the browser - or server - you are using.  Please contact the developers of those products.  This isn't a specification issue.
