### ISSUE TITLE
[feature request] To build General Multiplexing Question/Answer Protocol(TCP)

### ISSUE THREAD

**Issue by diyism** [http2/http2-spec#766]
I think HTTP2 is very good about multiplexing communication based on frames.

But i think we need a standard "General Multiplexing Question/Answer Protocol(TCP)" that abstracted from HTTP2. I abbreviate it as GMQAP.

Since HTTP is also a Question/Answer(QA) protocol, we can run any QA protocol on GMQAP, not only HTTP.

If we have built GMQAP, for example, on nginx, we can supply the same service on both HTTP and GMQAP protocols, the HTTP port accepts internet requests, the GMQAP port accepts intranet requests, but the backend is the same php-fpm. Because the two protocols are both QA protocol, we can prefix the same heads to GMQAP to transform it into HTTP data structure.

**Comment by mnot** [comment]
This is off-topic for this repo.
